version: '3.7'

services:
  gradle6:
    image: serialt/okteto-gradle:6.5
    build:
      context: .
      dockerfile: gradle/Dockerfile
      args:
        VERSION: "6.5.1" 
       
  gradle8:
    image: serialt/okteto-gradle:8.2.1-jdk17
    build:
      context: .
      dockerfile: gradle/Dockerfile
      args:
        VERSION: "8.2.1-jdk17"
  maven:
    image: serialt/okteto-maven:3
    build:
      context: .
      dockerfile: maven/Dockerfile
      args:
        VERSION: "3"

