version: '3.7'

services:
  dotnetcore3:
    image: serialt/okteto-dotnetcore:3
    build:
      context: .
      dockerfile: dotnetcore/Dockerfile
      args:
        VERSION: "3.1"
  dotnetcore6:
    image: serialtokteto-dotnetcore:6
    build:
      context: .
      dockerfile: dotnetcore/Dockerfile
      args:
        VERSION: "6.0"

  